# docker-compose.yml
version: "3"
services:
  postgres:
    image: docker.io/library/postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-ticketworld}
      POSTGRES_USER: ${DB_USERNAME:-ticketworld}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  node:
    image: docker.io/library/node:16
    depends_on:
      - postgres
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - RESERVATION_EXPIRATION_TIME=15m
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgres:5432
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    command: "npm start"
