# docker-compose.yml
version: "3"
services:
  postgres:
    image: docker.io/library/postgres:14
    restart: always
    # user: "2000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ticketworld}
      POSTGRES_USER: ${POSTGRES_USER:-ticketworld}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  node:
    image: docker.io/library/node:16
    depends_on:
      - postgres
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    command: "npm start"
